# Generated by Django 3.1.4 on 2021-01-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210120_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_exist',
            field=models.BooleanField(default=True),
        ),
    ]
