# Generated by Django 3.1.4 on 2021-01-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_product_exist'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_object_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
