# Generated by Django 3.1.4 on 2021-01-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_object_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_exist',
            field=models.BooleanField(default=True, verbose_name='موجودی'),
        ),
    ]
