# Generated by Django 3.1.4 on 2021-01-31 10:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210127_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_object_manager',
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=70),
        ),
    ]
