# Generated by Django 3.1.4 on 2021-02-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
