# Generated by Django 3.1.4 on 2021-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_gallery',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
