# Generated by Django 3.1.4 on 2021-02-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_gallery',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
